[package]
name = "shimadzu_lab_solutions_helper"
version = "0.2.1"
edition = "2024"

[dependencies]
eframe = { version = "0.35.0", features = ["persistence"] }
egui = "0.35.0"
egui_dnd = "0.16.0"
egui_plot = "0.36.0"
egui-phosphor = "0.13.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.24.0", features = ["v4", "serde", "js"] }

# native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.11"
# tokio = { version = "1.53.1", features = ["full"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

[workspace.metadata.release]
# Запускаем git-cliff перед релизным коммитом. 
# {{version}} — это переменная, куда cargo-release подставит новую версию.
pre-release-hook = [
    "git",
    "cliff",
    "-o",
    "CHANGELOG.md",
    "--tag",
    "{{version}}",
]

# Шаблон сообщения для релизного коммита (в стиле Conventional Commits)
pre-release-commit-message = "chore(release): v{{version}}"

# Шаблон имени тега
tag-name = "v{{version}}"

# Если вы НЕ планируете публиковать пакет на crates.io (например, это приватный бэкенд),
# обязательно добавьте эту строку, чтобы cargo-release пропустил шаг публикации:
publish = false
